// Environment Configuration (Auto-generated by build.js — DO NOT EDIT MANUALLY)
// Run: node build.js to regenerate.

window.EXPLYRA_CONFIG = {
    "firebase": {
        "apiKey": "AIzaSyDadazHFf525KrsOoQWUP5yJ7q7uxyf3lw",
        "authDomain": "explyras.firebaseapp.com",
        "databaseURL": "https://explyras-default-rtdb.asia-southeast1.firebasedatabase.app",
        "projectId": "explyras",
        "storageBucket": "explyras.firebasestorage.app",
        "messagingSenderId": "411853553644",
        "appId": "1:411853553644:web:eca79eab846b6a5149cac9",
        "measurementId": "G-TFBZ5GZ22C"
    },
    "ai": {
        "model": "gemini-2.5-flash",
        "apiKey": "HANDLED_BY_PROXY",
        "geminiKey": "AIzaSyDefIPTvfbaZtW4yD47mzWotFwdDHrut2E"
    },
    "analyticsId": "G-TFBZ5GZ22C",
    "emailApp": {
        "cloudflareZoneId": "17279e3699e4721a9952206ddbe8b1ee",
        "cloudflareToken": "HANDLED_BY_PROXY",
        "resendKey": "HANDLED_BY_PROXY"
    },
    "imagekit": {
        "publicKey": "public_A7ZHxCiIBfl/fxzXlk1tXUUR+B4=",
        "url": "https://upload.imagekit.io/api/v1/files/upload"
    },
    "emailjs": {
        "publicKey": "i1GEROAXLarlKvxnp"
    },
    "imgbb": {
        "url": "/api/imgbb",
        "apiKey": "HANDLED_BY_PROXY"
    }
};
