name: Minify and Deploy
on:
  push:
    branches:
      - main  # Jab bhi main branch pe push karoge, ye chalega

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Minify Files
        run: |
          mkdir -p dist
          # Sirf zaroori files copy karo, 'dist' aur 'node_modules' ko chod kar
          rsync -av --exclude='dist' --exclude='node_modules' --exclude='.git' --exclude='.github' . dist/
          
          # 'minify' tool install aur run karo
          npm install -g minify
          find dist -name "*.js" -o -name "*.css" -o -name "*.html" | xargs -I {} minify -o {} {}

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          vercel-args: '--prod'
          working-directory: ./dist